{
    'name': 'Field Force - Routes (Beats / Patches)',
    'version': '19.0.1.1.0',
    'category': 'Human Resources/Field Force',
    'summary': 'Route types per department (beat, patch...), routes by district, assigned routes, daily plans',
    'author': 'Field Force Suite',
    'depends': ['ff_visits', 'ff_attendance'],
    'data': [
        'security/ff_beat_security.xml',
        'security/ir.model.access.csv',
        'data/ff_beat_data.xml',
        'wizard/ff_beat_assign_wizard_views.xml',
        'views/ff_route_type_views.xml',
        'views/ff_beat_views.xml',
        'views/ff_beat_plan_views.xml',
        'views/ff_route_distance_views.xml',
        'views/hr_employee_views.xml',
        'views/ff_beat_menus.xml',
    ],
    'installable': True,
    'license': 'LGPL-3',
}
