{
    'name': 'Field Force - Routes & Journey Plans',
    'version': '19.0.1.3.0',
    'category': 'Human Resources/Field Force',
    'summary': 'Route types per department, routes by district, monthly journey plans with per-customer '
               'planned visits, templates and automatic visited / missed tracking',
    'author': 'Field Force Suite',
    'depends': ['ff_visits', 'ff_attendance'],
    'data': [
        'security/ff_beat_security.xml',
        'security/ir.model.access.csv',
        'data/ff_beat_data.xml',
        'data/ff_beat_cron.xml',
        'wizard/ff_beat_assign_wizard_views.xml',
        'wizard/ff_route_plan_apply_wizard_views.xml',
        'views/ff_route_type_views.xml',
        'views/ff_beat_views.xml',
        'views/ff_route_plan_views.xml',
        'views/ff_beat_plan_views.xml',
        'views/ff_route_distance_views.xml',
        'views/hr_employee_views.xml',
        'views/res_partner_views.xml',
        'views/ff_beat_menus.xml',
    ],
    'installable': True,
    'license': 'LGPL-3',
}
